-- Insert sample news data
INSERT INTO public.news (title, content, excerpt, date, image, category, slug, featured, read_time, author) VALUES
('LSF Launches New Legal Aid Campaign', 'Full content about the new legal aid campaign...', 'LSF has launched a comprehensive legal aid campaign to reach underserved communities across Tanzania.', '2025-01-15', '/lovable-uploads/mama samia legal aid campaingn.jpg', 'Innovation', 'lsf-launches-legal-aid-campaign', true, '5 min read', 'LSF Communications Team'),
('Community Paralegals Training Success', 'Full content about the training success...', 'Over 500 community paralegals completed advanced training programs, expanding access to justice in rural areas.', '2025-01-10', '/lovable-uploads/paralegals -2.png', 'Training', 'community-paralegals-training', true, '3 min read', 'LSF Programs Team'),
('Land Rights Victory for Women Farmers', 'Full content about the land rights victory...', 'A landmark case resulted in 200 women farmers securing land titles, setting a precedent for women''s property rights.', '2025-01-05', '/lovable-uploads/wanawake tunaweza image.jpg', 'Legal Victory', 'land-rights-victory-women', true, '7 min read', 'LSF Legal Team'),
('Digital Transformation in Legal Services', 'Full content about digital transformation...', 'LSF introduces new digital tools to streamline legal aid services and improve client access.', '2025-01-01', '/lovable-uploads/haki yangu app uzinuzi.webp', 'Innovation', 'digital-transformation-legal-services', false, '4 min read', 'LSF Tech Team'),
('Partnership with International Organizations', 'Full content about the partnership...', 'LSF strengthens partnerships with international organizations to expand legal empowerment programs.', '2024-12-28', '/lovable-uploads/LSF with partner meeting.jpg', 'Outreach', 'partnership-international-organizations', false, '6 min read', 'LSF Partnerships Team'),
('Annual Impact Report 2024', 'Full content about the annual impact...', 'LSF releases comprehensive impact report showing significant improvements in access to justice across Tanzania.', '2024-12-20', '/lovable-uploads/LSF 2024 ANNUAL REPORT (Mobile Video).png', 'Training', 'annual-impact-report-2024', false, '8 min read', 'LSF Research Team');

-- Insert sample publications data
INSERT INTO public.publications (title, description, excerpt, date, type, image, file_url, featured, download_count, file_size, pages, category) VALUES
('Annual Report 2024', 'Comprehensive annual report covering LSF''s activities and impact in 2024', 'This report provides a detailed overview of LSF''s work, achievements, and impact across Tanzania in 2024.', '2025-01-01', 'Report', '/lovable-uploads/LSF 2024 ANNUAL REPORT (Mobile Video).png', '/files/annual-report-2024.pdf', true, 1250, '2.5 MB', '45 pages', 'Reports'),
('Legal Empowerment Guide', 'Practical guide for community paralegals and legal aid workers', 'A comprehensive guide covering essential legal concepts, procedures, and best practices for legal empowerment work.', '2024-12-15', 'Guide', '/lovable-uploads/paralegals -3.png', '/files/legal-empowerment-guide.pdf', true, 890, '1.8 MB', '32 pages', 'Guides'),
('Women''s Rights Toolkit', 'Resource toolkit for advancing women''s rights and gender equality', 'Practical tools and resources for promoting women''s rights, including legal frameworks and advocacy strategies.', '2024-12-01', 'Toolkit', '/lovable-uploads/wanawake tunaweza- image.jpg', '/files/womens-rights-toolkit.pdf', true, 567, '3.2 MB', '28 pages', 'Toolkits'),
('Land Rights Manual', 'Manual for understanding and advocating for land rights', 'Comprehensive manual covering land rights issues, legal frameworks, and advocacy strategies for rural communities.', '2024-11-20', 'Manual', '/lovable-uploads/mwanamke shamba.png', '/files/land-rights-manual.pdf', false, 423, '4.1 MB', '52 pages', 'Manuals'),
('Policy Brief: Access to Justice', 'Policy brief on improving access to justice in Tanzania', 'Analysis of current challenges and recommendations for improving access to justice across Tanzania.', '2024-11-10', 'Brief', '/lovable-uploads/paralegals -4.png', '/files/access-to-justice-brief.pdf', false, 234, '0.8 MB', '12 pages', 'Policy Briefs'),
('Research Report: Community Paralegals', 'Research findings on the effectiveness of community paralegal programs', 'Comprehensive research on the impact and effectiveness of community paralegal programs in rural Tanzania.', '2024-10-30', 'Research', '/lovable-uploads/LSF-HIGHLIGHT-PRALEGAL.png', '/files/community-paralegals-research.pdf', false, 189, '2.8 MB', '38 pages', 'Research');

-- Insert sample opportunities data
INSERT INTO public.opportunities (title, description, type, status, deadline, organization, location, employment_type, featured, requirements, responsibilities, application_url, salary_range) VALUES
('Volunteer Legal Assistant', 'Assist with case intake, community outreach, and paralegal coordination in regional offices.', 'Volunteer', 'open', '2025-07-25', 'LSF', 'Dar es Salaam, Tanzania', 'Volunteer', true, ARRAY['Legal background preferred', 'Strong communication skills', 'Commitment to social justice'], ARRAY['Case intake and documentation', 'Community outreach activities', 'Support paralegal coordination'], 'https://lsf.or.tz/careers/volunteer-legal-assistant', 'Volunteer position'),
('Internship – Digital Communication', 'Support social media, content writing, and digital campaigns across our platforms.', 'Internship', 'open', '2025-07-28', 'LSF', 'Remote / Dar es Salaam', 'Internship', true, ARRAY['Communication or marketing background', 'Social media experience', 'Strong writing skills'], ARRAY['Social media management', 'Content creation', 'Digital campaign support'], 'https://lsf.or.tz/careers/digital-communication-intern', 'Stipend provided'),
('Project Officer – Access to Justice', 'Coordinate regional activities, monitor paralegal programs, and report implementation progress.', 'Full Time', 'open', '2025-08-05', 'LSF', 'Mbeya, Tanzania', 'Full Time', true, ARRAY['Bachelor''s degree in relevant field', '3+ years project management experience', 'Experience in development sector'], ARRAY['Program coordination', 'Monitoring and evaluation', 'Stakeholder engagement'], 'https://lsf.or.tz/careers/project-officer', 'Competitive salary'),
('Legal Research Assistant', 'Support legal research initiatives and policy analysis for advocacy campaigns.', 'Part Time', 'open', '2025-08-15', 'LSF', 'Dar es Salaam, Tanzania', 'Part Time', false, ARRAY['Law degree or legal studies background', 'Research experience', 'Analytical skills'], ARRAY['Legal research', 'Policy analysis', 'Report writing'], 'https://lsf.or.tz/careers/legal-research-assistant', 'Hourly rate'),
('Communications Manager', 'Lead communications strategy, media relations, and public awareness campaigns.', 'Full Time', 'open', '2025-08-20', 'LSF', 'Dar es Salaam, Tanzania', 'Full Time', false, ARRAY['5+ years communications experience', 'Media relations skills', 'Strategic thinking'], ARRAY['Communications strategy', 'Media relations', 'Campaign management'], 'https://lsf.or.tz/careers/communications-manager', 'Competitive salary'),
('Finance Officer', 'Manage financial operations, budgeting, and donor reporting for programs.', 'Full Time', 'open', '2025-08-25', 'LSF', 'Dar es Salaam, Tanzania', 'Full Time', false, ARRAY['Accounting or finance degree', '3+ years NGO finance experience', 'Donor reporting skills'], ARRAY['Financial management', 'Budgeting', 'Donor reporting'], 'https://lsf.or.tz/careers/finance-officer', 'Competitive salary');
