// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vegjzxfdpnwqvyhvkwdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ2p6eGZkcG53cXZ5aHZrd2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODUyODksImV4cCI6MjA2ODA2MTI4OX0.lAkD9yo4-rPdBcnFOy4WvZw9UY7aWtnTcByJfG-is0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});